# Generated by Django 2.0.2 on 2018-02-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRLab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absolute_discount',
            fields=[
                ('retrievalmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IRLab.RetrievalMethod')),
                ('p_delta', models.FloatField()),
            ],
            bases=('IRLab.retrievalmethod',),
        ),
        migrations.CreateModel(
            name='Dirichlet_prior',
            fields=[
                ('retrievalmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IRLab.RetrievalMethod')),
                ('p_mu', models.FloatField()),
            ],
            bases=('IRLab.retrievalmethod',),
        ),
        migrations.CreateModel(
            name='Jelinek_mercer',
            fields=[
                ('retrievalmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IRLab.RetrievalMethod')),
                ('p_lambda', models.FloatField()),
            ],
            bases=('IRLab.retrievalmethod',),
        ),
        migrations.CreateModel(
            name='Okapi_bm25',
            fields=[
                ('retrievalmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IRLab.RetrievalMethod')),
                ('p_k1', models.FloatField()),
                ('p_b', models.FloatField()),
                ('p_k3', models.FloatField()),
            ],
            bases=('IRLab.retrievalmethod',),
        ),
        migrations.CreateModel(
            name='Pivoted_length',
            fields=[
                ('retrievalmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IRLab.RetrievalMethod')),
                ('p_s', models.FloatField()),
            ],
            bases=('IRLab.retrievalmethod',),
        ),
    ]
