# Generated by Django 2.0.2 on 2018-02-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IRLab', '0002_absolute_discount_dirichlet_prior_jelinek_mercer_okapi_bm25_pivoted_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retrievalmethod',
            old_name='user',
            new_name='author',
        ),
    ]
