# Generated by Django 2.0.2 on 2018-02-13 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRLab', '0009_auto_20180212_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=30)),
                ('_map', models.FloatField()),
                ('_ndcg', models.FloatField()),
                ('ranker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRLab.RetrievalMethod')),
            ],
        ),
    ]
