# Generated by Django 2.0.2 on 2018-02-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRLab', '0010_peformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='peformance',
            name='elapsed_time',
            field=models.FloatField(default=0.2),
            preserve_default=False,
        ),
    ]
