# Generated by Django 2.0.2 on 2018-02-23 04:09

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('IRLab', '0012_auto_20180213_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', froala_editor.fields.FroalaField()),
            ],
        ),
        migrations.CreateModel(
            name='Own_retrieval',
            fields=[
                ('retrievalmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IRLab.RetrievalMethod')),
                ('source', models.CharField(max_length=100000)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('IRLab.retrievalmethod',),
        ),
    ]
