# Generated by Django 2.0.2 on 2018-02-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRLab', '0015_own_retrieval_ranker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='absolute_discount',
            name='ranker_id_4_config',
            field=models.CharField(default='absolute-discount', max_length=70),
        ),
        migrations.AddField(
            model_name='dirichlet_prior',
            name='ranker_id_4_config',
            field=models.CharField(default='dirichlet-prior', max_length=70),
        ),
        migrations.AddField(
            model_name='jelinek_mercer',
            name='ranker_id_4_config',
            field=models.CharField(default='jelinek-mercer', max_length=70),
        ),
        migrations.AddField(
            model_name='okapi_bm25',
            name='ranker_id_4_config',
            field=models.CharField(default='bm25', max_length=70),
        ),
        migrations.AddField(
            model_name='own_retrieval',
            name='ranker_id_4_config',
            field=models.CharField(default='customzied-ranker', max_length=70),
        ),
        migrations.AddField(
            model_name='pivoted_length',
            name='ranker_id_4_config',
            field=models.CharField(default='pivoted-length', max_length=70),
        ),
    ]
