# Generated by Django 2.0.2 on 2018-04-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRLab', '0017_auto_20180417_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='peformance',
            name='avg_p_list',
            field=models.CharField(default='a', max_length=100000),
            preserve_default=False,
        ),
    ]
